### ISSUE TITLE
generate openfl with away3d

### ISSUE THREAD

**Issue by varadig** [kevinresol/hxgenjs#14]
I try to compile a simple away3d project, with hxgenjs.
Without hxgenjs is working, but with it i got thie:

`(anonymous function)	Uncaught ReferenceError: require is not defined Load3DS.js:1`
the first line of the file is 
`require("./Std")`

Ok so I add the requirejs to the index.html
`	<script type="text/javascript" src="http://requirejs.org/docs/release/2.2.0/minified/require.js"></script>
`
But after I got this:

```

F	m	requirejs	(anonymous function)	Uncaught Error: Module name "Std" has not been loaded yet for context: _. Use require([])
  
  
  
  
(anonymous function)	Uncaught ReferenceError: lime is not defined
  
F	P	(anonymous function)	Uncaught Error: Mismatched anonymous define() module: function (){return{Howler:t,Howl:n}}
```

What have I do?

thanks

**Comment by varadig** [comment]
here is my project.xml the:

```
<?xml version="1.0" encoding="utf-8"?>
<project>
	
	<meta title="Away3D Basic Load3DS" package="away3d.samples.basicload3ds" version="1.0.0" />
	<app main="Main" file="Load3DS" path="Export" />
	
	<window background="0x000000" orientation="landscape" />
	<window width="1024" height="700" if="desktop" />
	
	<source path="Source" />
	
	<haxelib name="away3d" />
	<haxelib name="hxgenjs"/>
	
	<assets path="Assets" rename="assets" />
	
</project>
```

**Comment by kevinresol** [comment]
You need bundle the files with packager such as webpack or browserify

**Comment by varadig** [comment]
thanks
