### ISSUE TITLE
getting error in tink_core

### ISSUE THREAD

**Issue by khuram99** [kevinresol/hxgenjs#16]
I'm trying to convert haxe to es6 version, but getting this error

tink_macro/0,14,1/src/tink/macro/Types.hx:20:` characters 8-12 : Unknown identifier : Some
/haxelib/tink_macro/0,14,1/src/tink/macro/Types.hx:23: characters 61-65 : Unknown identifier : None
/haxelib/tink_macro/0,14,1/src/tink/macro/Types.hx:24: characters 13-39 : Dynamic should be Void

Just wondering if I'm missing something here.

**Comment by kevinresol** [comment]
can you try upgrading all the dependencies? tink_macro 0.14.1 is pretty old

**Comment by khuram99** [comment]
yep i did. still getting the same error. now tink_macro is 0.16.3.

My haxe version is 3.2.1

**Comment by kevinresol** [comment]
Argh... I wrote this lib against haxe 3.4, and I think I am not gonna spend time to make it compatible with anything eariler. I think the best solution is to upgrade haxe. Sorry about that.

**Comment by khuram99** [comment]
ok make sense. thanks for help :)
