### ISSUE TITLE
Dce & abstracts

### ISSUE THREAD

**Issue by benmerckx** [kevinresol/hxgenjs#18]
Seems like hxgenjs generates output for all abstracts even if their implementation is unused (even with `-dce full`).

![image](https://user-images.githubusercontent.com/10584189/41820891-11e7620a-77d9-11e8-8b85-88b4c423fed9.png)

**Comment by kevinresol** [comment]
Are they empty?

**Comment by benmerckx** [comment]
There's still some left in my output without any statics, so I'm going to reopen this and investigate. They must be reaching the type processor in another way.

![image](https://user-images.githubusercontent.com/10584189/41865267-d83d009e-78ac-11e8-9839-87f6863a65ed.png)
