### ISSUE TITLE
support haxe4?

### ISSUE THREAD

**Issue by sonygod** [kevinresol/hxgenjs#30]
support haxe4?

public static function use() {
		if (!Context.defined('js')) return;
		**Context.onMacroContextReused**(function() return false);

//--------------------------------

@:deprecated
	public static function registerModuleReuseCall( modulePath : String, macroCall : String ) {
		throw "This method is no longer supported. See https://github.com/HaxeFoundation/haxe/issues/5746";
	}

	@:deprecated
	public static function onMacroContextReused( callb : Void -> Bool ) {
		throw "This method is no longer supported. See https://github.com/HaxeFoundation/haxe/issues/5746";
	}

**Comment by kevinresol** [comment]
I guess simply wrapping the offending line with `#if (haxe_ver < 4)` should be fine

**Comment by sonygod** [comment]
You cannot access the sys package while targeting js (for sys.io.File)

 after add meta

#if (haxe_ver < 4)
		Context.onMacroContextReused(function() return false);
		#end

**Comment by kevinresol** [comment]
Closed by 5e87fc7e9a883f51a990fcbf51a7335a2c308d0b
