### ISSUE TITLE
Binding 'eval' in strict mode (108:20) 

### ISSUE THREAD

**Issue by sonygod** [kevinresol/hxgenjs#31]
hi,just test with heaps framework ,and got this error.

haxe  -lib heaps -lib hxgenjs -cp src -cp samples -js Y:/test/test/src/components/haxe/haxetest.js -main Main -dce no -D hxextern

haxe version:3.4.7

[shareshader.js](https://gist.github.com/sonygod/72196705c01aa7dd98d3d32b67512c34)
run in vue

![image](https://user-images.githubusercontent.com/748320/53692010-8d4c0f80-3dc3-11e9-87cc-8003482edcc7.png)

**Comment by elsassph** [comment]
Visibly Heaps uses `eval` as function argument name somewhere. It looks like the webpack bundling (looks like Babel processing involved to process Vue files) doesn't allow using this name in the code.

You may have to

**Comment by sonygod** [comment]
@elsassph  current hxgenjs is not work for Chrome  ,May be it's only for Node.js dev.

it's export by custom define exports ,not work 

@kevinresol

**Comment by kevinresol** [comment]
Did you bundle on chrome?

**Comment by sonygod** [comment]
build haxe code for vue dev,run in chrome browser.

**Comment by kevinresol** [comment]
hxgenjs emits CommonJS code (sync `require`) and that won't work on browser by default. You need to bundle it using webpack or browsify, etc. Did you do so? And what is the exact error you are getting?

**Comment by sonygod** [comment]
yes ,I use Vue-cli 3.4  tool to build and wepack  the sources from hxgenjs.

after webpack,it's throw exports is not defined.

I can give you small project example later.

build args

...  main Main -dce full -D hxextern


[here](https://gist.github.com/sonygod/8340c2c2e9bb456d298355b9ba4df5c6) is examples files and error

**Comment by kevinresol** [comment]
did you try patching the `eval` argument name to something else?

**Comment by sonygod** [comment]
I don't have use eval anywhere

,it's seem include Heaps engine ,for shader .

**Comment by kevinresol** [comment]
Doesn't seem to be a problem of hxgenjs. Closing for now.
