### ISSUE TITLE
C:\HaxeToolkit\haxe\std/js/Boot.hx:30: lines 30-34 : Could not find super call

### ISSUE THREAD

**Issue by sonygod** [kevinresol/hxgenjs#34]
C:\HaxeToolkit\haxe\std/js/Boot.hx:30: lines 30-34 : Could not find super call

-lib hxgenjs
-dce=full
-lib ds
-D js-es=6
-lib random

**Comment by sonygod** [comment]
haxe 4.0 rc3

**Comment by sonygod** [comment]
@kevinresol

**Comment by kevinresol** [comment]
Not enough information to reproduce

**Comment by sonygod** [comment]
I will send a sample project to test.
